// CUV (public domain). NIV is intentionally absent: requested at runtime.
// CUV source: https://b.ibible.hk/bible/9/1co/13 ; reviewed 2026-09-30.
const lines = [
  '我/若/能/说/万人/的/方言/，/并/天使/的/话语/，/却/没有/爱/，/我/就/成了/鸣/的/锣/，/响/的/钹/一般/。',
  '我/若/有/先知/讲道/之/能/，/也/明白/各样/的/奥秘/，/各样/的/知识/，/而且/有/全备/的/信/，/叫/我/能够/移山/，/却/没有/爱/，/我/就/算不得/什么/。',
  '我/若/将/所有/的/赒济/穷人/，/又/舍/己身/叫/人/焚烧/，/却/没有/爱/，/仍然/与/我/无益/。',
  '爱/是/恒久/忍耐/，/又/有/恩慈/；/爱/是/不/嫉妒/；/爱/是/不/自夸/，/不/张狂/，',
  '不/做/害羞/的/事/，/不/求/自己/的/益处/，/不/轻易/发怒/，/不/计算/人/的/恶/，',
  '不/喜欢/不义/，/只/喜欢/真理/；',
  '凡事/包容/，/凡事/相信/，/凡事/盼望/，/凡事/忍耐/。',
  '爱/是/永不/止息/。/先知/讲道/之/能/终必/归于/无有/；/说/方言/之/能/终必/停止/；/知识/也/终必/归于/无有/。',
  '我们/现在/所/知道/的/有限/，/先知/所/讲/的/也/有限/，',
  '等/那/完全/的/来到/，/这/有限/的/必/归于/无有/了/。',
  '我/作/孩子/的/时候/，/话语/像/孩子/，/心思/像/孩子/，/意念/像/孩子/，/既/成了/人/，/就/把/孩子/的/事/丢弃/了/。',
  '我们/如今/仿佛/对着/镜子/观看/，/模糊不清/（/原文/作/如同/猜谜/）/；/到/那时/就要/面对面/了/。/我/如今/所/知道/的/有限/，/到/那时/就/全/知道/，/如同/主/知道/我/一样/。',
  '如今/常存/的/有/信/，/有/望/，/有/爱/这/三样/，/其中/最大/的/是/爱/。',
];

// [Chinese term, pinyin, English gloss, child-friendly Chinese explanation, image idea, English lookup aliases]
export const entries = [
  ['成了','chéng le','became','变成了。',null,[]],
  ['求','qiú','seek; ask for','想要得到。',null,[]],
  ['喜欢','xǐ huān','like; delight in','觉得好，心里愿意。',null,['delight','rejoices']],
  ['现在','xiàn zài','now','这个时候。',null,[]],
  ['等','děng','wait; until','等到某个时候。',null,[]],
  ['作','zuò','be; do','这里是“还是孩子”的意思。',null,[]],
  ['孩子','hái zi','child','年纪还小的人。',null,[]],
  ['像','xiàng','like','和某样东西相似。',null,[]],
  ['全','quán','all; fully','全部。',null,[]],
  ['主','zhǔ','the Lord','这里指神。',null,[]],
  ['一样','yí yàng','the same','相同。',null,[]],
  ['爱','ài','love','真心关心别人，也用行动表达。','一个孩子留出身边的位置，邀请另一个孩子坐下。',['love']],
  ['忍耐','rěn nài','be patient','愿意等一等，给别人时间。','一个孩子等朋友把话讲完，再开口。',['patient','patience','perseveres']],
  ['恩慈','ēn cí','kindness','温柔地对待别人，愿意帮助人。','一个孩子弯下身，帮朋友捡起散落的蜡笔。',['kind','kindness']],
  ['嫉妒','jí dù','envy','看见别人有好东西，心里不高兴。','朋友得到新画笔，另一个孩子先看看自己的笔，再和他一起画。',['envy','envies']],
  ['自夸','zì kuā','boast','总说自己很厉害，想让别人羡慕。','孩子展示自己的积木，也给朋友留下展示的位置。',['boast','boasts']],
  ['张狂','zhāng kuáng','act proudly','觉得自己最了不起，看不起别人。','两个孩子把自己的作品放在同样高的桌面上。',['proud']],
  ['恒久','héng jiǔ','lasting','不是只做一次，而是长久地这样做。','同一对朋友在不同日子里互相等候。',[]],
  ['全备','quán bèi','complete','完全，没有缺少。',null,[]],
  ['万人','wàn rén','many people','这里是说很多很多人。',null,['mankind']],
  ['方言','fāng yán','tongues; languages','这里指不同的语言。','两个孩子用不同语言谈论同一张画。',['tongues','languages']],
  ['天使','tiān shǐ','angel','圣经里传达神消息的使者。',null,['angels']],
  ['话语','huà yǔ','words','说出来的话。',null,['words','speak']],
  ['鸣','míng','make a sound','发出声音。',null,[]],
  ['锣','luó','gong','一种圆圆的金属乐器，敲起来很响。','一面圆锣和一根敲锣的小槌。',['gong']],
  ['响','xiǎng','sound; ring','发出可以听见的声音。',null,['resounding']],
  ['钹','bó','cymbal','两片圆形金属片，碰在一起会发出响声。','两片圆形铜钹，旁边有弯曲的声音线。',['cymbal','clanging']],
  ['一般','yì bān','like; the same as','这里是说“就像那样”。',null,[]],
  ['先知','xiān zhī','prophet','圣经里向人传达神话语的人。',null,['prophecy','prophecies']],
  ['讲道','jiǎng dào','speak God’s message','向别人讲神的话。',null,[]],
  ['之','zhī','of','这里的“之”和“的”意思相近。',null,[]],
  ['明白','míng bai','understand','知道是什么意思。','一个孩子指着画解释，朋友点头。',['understand']],
  ['各样','gè yàng','all kinds','不同种类的。',null,[]],
  ['奥秘','ào mì','mystery','我们还不容易明白的事。',null,['mysteries']],
  ['知识','zhī shi','knowledge','我们学到、知道的东西。','打开的书、尺子和孩子观察的叶子。',['knowledge']],
  ['而且','ér qiě','and also','把后面的一件事也加上。',null,[]],
  ['信','xìn','faith; trust','相信神，也信靠祂。','一个孩子牵着信任的大人的手，走在小路上。',['faith','trusts']],
  ['能够','néng gòu','can; be able to','有能力做到。',null,['can']],
  ['移山','yí shān','move mountains','把山移走，形容很大的能力。','一座山与很小的孩子，用大小对比表达。',['mountains']],
  ['算不得','suàn bu dé','count as nothing','不能算作。',null,['nothing']],
  ['将','jiāng','take; use','这里是“把”的意思。',null,[]],
  ['所有','suǒ yǒu','all','全部。',null,['all']],
  ['赒济','zhōu jì','give help to people in need','把食物或财物分给有需要的人。','把一篮食物递给需要食物的邻居。',['give','poor']],
  ['穷人','qióng rén','people in need','缺少生活所需东西的人。',null,[]],
  ['舍','shě','give up','放下或交出自己所有的。',null,['surrender']],
  ['己身','jǐ shēn','one’s own body','自己的身体。',null,['body']],
  ['焚烧','fén shāo','burn','被火烧。',null,[]],
  ['仍然','réng rán','still','还是和前面说的一样。',null,[]],
  ['与','yǔ','to; with','这里用来连接“我”。',null,[]],
  ['无益','wú yì','no benefit','没有帮助，没有益处。',null,['gain']],
  ['害羞','hài xiū','disgraceful (in this sentence)','这里说的是做不合宜、让人受羞辱的事，不是说性格害羞不好。',null,['dishonor']],
  ['益处','yì chu','benefit','对人有帮助的好处。',null,['self-seeking']],
  ['轻易','qīng yì','easily','很快就、很容易就。',null,['easily']],
  ['发怒','fā nù','become angry','生气、发脾气。','一个孩子生气时先停一停，慢慢呼吸。',['angered','angry']],
  ['计算','jì suàn','keep count','这句话里是把别人做错的事一件件记着。',null,['record','keeps']],
  ['恶','è','wrong; evil','伤害别人、做错的事。',null,['wrongs','evil']],
  ['不义','bú yì','wrongdoing','不诚实、不公平的事。',null,[]],
  ['真理','zhēn lǐ','truth','真实、正确的道理。','孩子打翻杯子后，诚实地指着自己说明经过。',['truth']],
  ['凡事','fán shì','in everything','在各种事情上。',null,['always']],
  ['包容','bāo róng','bear with; protect','愿意体谅别人，陪他一起改进。','画画时颜色溅到纸上，两个孩子一起想办法。',['protects']],
  ['相信','xiāng xìn','believe; trust','愿意信任。',null,['believe','believes']],
  ['盼望','pàn wàng','hope','期待好的事情会发生。','两个孩子给刚发芽的小植物浇水。',['hope','hopes']],
  ['永不','yǒng bù','never','一直都不会。',null,['never']],
  ['止息','zhǐ xī','come to an end','停下来，结束。',null,['fails','cease']],
  ['终必','zhōng bì','will eventually','到了最后，一定会。',null,[]],
  ['归于','guī yú','come to; become','最后成为某一种情形。',null,[]],
  ['无有','wú yǒu','nothing; no longer there','不再有了。',null,[]],
  ['停止','tíng zhǐ','stop','不再继续。',null,[]],
  ['有限','yǒu xiàn','limited; in part','只知道一部分，还没有全部知道。','一块拼图旁边留着还没拼好的位置。',['part','partially']],
  ['完全','wán quán','complete','完整，没有缺少。','几块拼图拼成一整幅图。',['completeness','complete']],
  ['心思','xīn si','thoughts','心里在想的事。',null,['thought']],
  ['意念','yì niàn','ideas','心里的想法。',null,['reasoned']],
  ['既','jì','since; already','既然已经。',null,[]],
  ['丢弃','diū qì','put away','放下，不再保留。',null,['put']],
  ['如今','rú jīn','now','现在。',null,['now']],
  ['仿佛','fǎng fú','as if','好像。',null,[]],
  ['对着','duì zhe','facing','朝向那一边。',null,[]],
  ['镜子','jìng zi','mirror','可以照见自己样子的东西。','一面能看到孩子脸庞的小镜子。',['mirror']],
  ['观看','guān kàn','look at','仔细看。',null,['see']],
  ['模糊不清','mó hu bù qīng','unclear','看不清楚，不够清楚。','同一片叶子：一边隔着雾玻璃，一边直接看。',['reflection']],
  ['原文','yuán wén','original wording','最初写下的文字。',null,[]],
  ['猜谜','cāi mí','solve a riddle','根据线索猜出答案。',null,[]],
  ['那时','nà shí','then','到了那个时候。',null,['then']],
  ['就要','jiù yào','will then','将会。',null,[]],
  ['面对面','miàn duì miàn','face to face','两个人朝着对方，可以直接看见彼此。','两个孩子坐在同样高度，面对面谈话。',['face']],
  ['如同','rú tóng','just as','就像。',null,[]],
  ['常存','cháng cún','remain','一直存在。',null,['remain']],
  ['望','wàng','hope','盼望，期待。',null,[]],
  ['三样','sān yàng','three things','三种东西。',null,['three']],
  ['其中','qí zhōng','among them','在刚才说的这些里面。',null,['these']],
  ['最大','zuì dà','greatest','在这里指最重要。',null,['greatest']],
];

const explanations = [
  ['会说很多话，也要真心关心别人。','Our words matter when we care about the people hearing them.'],
  ['知道很多、能力很强，也需要爱。','Knowing a lot and being able to do a lot still need love.'],
  ['帮助人时，心里也要真的关心他。','When we help someone, caring about that person matters.'],
  ['爱会耐心等候，温柔待人，不总是夸自己。','Love gives people time and treats them kindly.'],
  ['爱会顾到别人，不只想着自己，也不总翻旧账。','Love considers others and does not keep bringing up old wrongs.'],
  ['爱喜欢诚实和正确的事，不为伤害人的事高兴。','Love is glad about what is true and right.'],
  ['爱愿意体谅、信任、盼望，也愿意坚持。','Love makes room for others, trusts, hopes, and keeps going.'],
  ['许多能力会过去，爱仍然长存。','Abilities may come to an end; love lasts.'],
  ['我们懂得的只是其中一部分。','We only understand part of the picture.'],
  ['这里盼望有一天，我们能明白得更完整。','This looks ahead to a time of fuller understanding.'],
  ['长大时，我们说话和想事情的方式也会改变。','As we grow, the way we speak and think changes.'],
  ['我们现在还不能全明白，像看不清楚的镜子。','We do not yet see everything clearly.'],
  ['信、望、爱都长存，其中最大的是爱。','Faith, hope, and love remain, and love matters most.'],
];

export const love = {
  id:'love',title:'爱的篇章',reference:'哥林多前书 13 章',book:'1CO',chapter:13,
  verses:lines.map((line,i)=>({n:i+1,tokens:line.split('/'),explainZh:explanations[i][0],explainEn:explanations[i][1]})),
  sections:[
    {title:'有爱，才有意义',range:[1,4],intro:'会很多本领，也可以温柔地关心别人。'},
    {title:'把爱做出来',range:[5,8],intro:'在小小的事情上，练习关心彼此。'},
    {title:'长大，也继续学着爱',range:[9,13],intro:'我们都有还不懂的事，也都有可以教给别人的东西。'},
  ],
};

export function makeSeed(reference){
 return {id:'seed',title:'种子与好土',reference:'马可福音 4:1–9',book:'MRK',chapter:4,
 verses:reference.verses.map(v=>({...v,explainZh:'想一想，这节里发生了什么？你可以用自己的话讲给对方听。',explainEn:reference.explain[v.n]||''})),
 sections:[
 {title:'听一个撒种的故事',range:[1,4],intro:'一起来听，再把故事讲给对方。'},
 {title:'不同地方的种子',range:[5,9],intro:'同样的种子，在不同的地方会怎么样？'},]};
}
